services:
  daily-reflection:
    build:
      context: .
    container_name: daily
    environment:
      VIRTUAL_HOST: daily.khalil.ink
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: daily.khalil.ink
      LETSENCRYPT_EMAIL: mail@khalil.ink
      DATABASE_URL: ${DATABASE_URL}
      SALT_ROUND: ${SALT_ROUND}
      JWT_SECRET: ${JWT_SECRET}


networks:
  default:
    external:
      name: nginx-proxy