services:
  daily-reflection:
    build:
      context: .
    container_name: daily
    environment:
      VIRTUAL_HOST: daily.khalil.ink
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: daily.khalil.ink
      LETSENCRYPT_EMAIL: mail@khalil.ink
    env_file:
      - path: ./.env
        required: true



networks:
  default:
    external:
      name: nginx-proxy